[window] 
	position = "none"
	padding = { x = 0, y = 0 }
	dynamic_padding = true
	opacity = 0.5

[font]
  normal = { family = "IBM 3270", style = "regular" }
	offset = { x = 0, y = 1}
	size = 12

[scrolling]
	history = 10000

[colors]
  cursor = { cursor = "#83A598" }
	[colors.primary]
  background = "#282828"

[cursor]
	style = { shape = "block", blinking = "On" }
	blink_timeout = 0
